name = "Dcc"
version = "0.1.0"
defaultTargets = ["Dcc", "docs"]

[[lean_lib]]
name = "Dcc"

[[lean_lib]]
name = "Docs"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.26.0"

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso"
rev = "v4.26.0-rc2"

[[require]]
name = "subverso"
git = "https://github.com/leanprover/subverso"
rev = "2aa08940ec078fdf3d4c168bf60091d07ccccbfb"

[[lean_exe]]
name = "docs"
root = "Main"
srcDir = "."
