name = "Dam"
version = "0.1.0"
defaultTargets = ["dam"]

[[lean_lib]]
name = "Dam"

[[lean_exe]]
name = "dam"
root = "Main"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"

