name = "Dcc"
version = "0.1.0"
defaultTargets = ["Dcc", "docs"]

[[lean_lib]]
name = "Dcc"

[[lean_lib]]
name = "Docs"

[[require]]
name = "subverso"
git = "https://github.com/lexzaiello/subverso"

[[require]]
name = "verso"
git = "https://github.com/leanprover/verso"
rev = "v4.26.0-rc2"

[[lean_exe]]
name = "docs"
root = "Main"
srcDir = "."
