name = "Cm"
version = "0.1.0"
defaultTargets = ["Cm"]
testDriver = "tests"

[[require]]
name = "lspec"
git = "https://github.com/yatima-inc/lspec.git"
rev = "main"

[[lean_lib]]
name = "Cm"

[[lean_exe]]
name = "cm"
root = "Main"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"

[[lean_exe]]
name = "tests"
root = "Tests"
supportInterpreter = true