name = "Cm"
version = "0.1.0"
defaultTargets = ["Cm"]

[[lean_lib]]
name = "Cm"

[[lean_exe]]
name = "cm"
root = "Main"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"

