name = "zkdtt"
version = "0.1.0"
defaultTargets = ["zkdtt"]

[[lean_lib]]
name = "Zkdtt"

[[lean_exe]]
name = "zkdtt"
root = "Main"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"

